apiVersion: v2
name: logging-stack
description: EFK (Elasticsearch, Fluentd, Kibana) logging stack for CRM application
type: application
version: 1.0.0
appVersion: "8.5.1"

dependencies:
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled

  - name: kibana
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: kibana.enabled

  - name: fluentd
    version: 0.5.2
    repository: https://fluent.github.io/helm-charts
    condition: fluentd.enabled
