{{- if .Values.elasticsearch.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "crm-stack.fullname" . }}-es-index-template
  labels:
    {{- include "crm-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch-setup
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ include "crm-stack.fullname" . }}-es-index-template
    spec:
      restartPolicy: OnFailure
      containers:
      - name: create-index-template
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Wait for Elasticsearch to be ready
          until curl -k -u elastic:${ES_PASSWORD} \
            https://elasticsearch-master:9200/_cluster/health?wait_for_status=yellow&timeout=60s; do
            echo "Waiting for Elasticsearch to be ready..."
            sleep 5
          done

          # Create index template for logs-*
          curl -k -u elastic:${ES_PASSWORD} \
            -X PUT "https://elasticsearch-master:9200/_index_template/logs-template" \
            -H 'Content-Type: application/json' \
            -d '{
              "index_patterns": ["logs-*"],
              "template": {
                "settings": {
                  "number_of_shards": 1,
                  "number_of_replicas": 0
                },
                "mappings": {
                  "dynamic": true,
                  "properties": {
                    "@timestamp": { "type": "date" },
                    "log": {
                      "type": "text",
                      "fields": {
                        "keyword": { "type": "keyword", "ignore_above": 256 }
                      }
                    },
                    "kubernetes": {
                      "properties": {
                        "namespace_name": { "type": "keyword" },
                        "pod_name": { "type": "keyword" },
                        "container_name": { "type": "keyword" },
                        "host": { "type": "keyword" }
                      }
                    },
                    "crm": { "type": "object", "dynamic": true },
                    "mongodb": { "type": "object", "dynamic": true }
                  }
                }
              }
            }'

          echo "Elasticsearch index template created successfully"
        env:
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials
              key: password
{{- end }}