apiVersion: v2
name: crm-stack
description: Umbrella Helm chart for CRM application with MongoDB database
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: crm-app
    version: "1.0.0"
    repository: "file://./charts/crm-app"
  - name: mongodb
    version: "1.0.0"
    repository: "file://./charts/mongodb"
