apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crm-app.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "crm-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "crm-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crm-app.selectorLabels" . | nindent 8 }}
        {{- with .Values.global.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
          protocol: TCP
        env:
        - name: MONGO_URI
          value: "mongodb://{{ .Values.global.mongodb.host }}.{{ .Values.global.namespace }}.svc.cluster.local:{{ .Values.global.mongodb.port }}/{{ .Values.global.mongodb.database }}"
        - name: PORT
          value: "{{ .Values.service.targetPort }}"
        - name: ENVIRONMENT
          value: "{{ .Values.global.environment }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- if .Values.healthCheck.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthCheck.path }}
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.healthCheck.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.healthCheck.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.healthCheck.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthCheck.path }}
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.healthCheck.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.healthCheck.readinessProbe.timeoutSeconds }}
        {{- end }}
